@echo off
cd "c:\Semester 6\PENALARAN KOMPUTER\cbr_project-main\cbr_project-main"
echo Menjalankan Notebook 01...
python -m nbconvert --to notebook --execute --inplace notebooks\01_case_base.ipynb
echo Menjalankan Notebook 02...
python -m nbconvert --to notebook --execute --inplace notebooks\02_case_representation.ipynb
echo Menjalankan Notebook 03...
python -m nbconvert --to notebook --execute --inplace notebooks\03_case_retrieval.ipynb
echo Menjalankan Notebook 04...
python -m nbconvert --to notebook --execute --inplace notebooks\04_solution_reuse.ipynb
echo Menjalankan Notebook 05...
python -m nbconvert --to notebook --execute --inplace notebooks\05_evaluation.ipynb
echo Selesai!
